spring.application.name=Proyecto
Tomcat started on port(s): 8080 (http) with context path ''
springdoc.swagger-ui.path=/swagger-ui.html

spring.datasource.url=jdbc:mariadb://localhost:3307/proyecto_supermercado
spring.datasource.username=root
spring.datasource.password=Nicol
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
JWT_SECRET=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9/eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ/SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c


