
package vistas;

import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import vistas.VentanaPrincipal;
import modelos.*;
import controller.ProductoController;
import excepciones.CodigoNoEncontrado;
import excepciones.NotificarExito;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.table.DefaultTableModel;
import repository.ProductoRepository;
import service.ProductoService;
import java.util.ArrayList;

/**
 *
 * @author NICOL VALERIA
 */
public class ProductosVistas extends javax.swing.JFrame {
    VentanaPrincipal vp = new VentanaPrincipal();
    ProductoService control;
     FuncionExitosa exito = new FuncionExitosa ();
     NoEncontrado noEncontrado = new NoEncontrado ();

    /**
     * Creates new form Productos
     */
    public ProductosVistas(ProductoService control) {
        exito.setVisible(false);
        noEncontrado.setVisible(false);
        this.control = control;
        FondoPanel fondo = new FondoPanel();
        this.setContentPane(fondo);
        initComponents();
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        agregarButton = new javax.swing.JButton();
        eliminarButton = new javax.swing.JButton();
        modificarButton = new javax.swing.JButton();
        buscarButton = new javax.swing.JButton();
        regresarButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        cad = new javax.swing.JTextField();
        cant = new javax.swing.JTextField();
        cat = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(54, 33, 26));

        agregarButton.setBackground(new java.awt.Color(72, 36, 0));
        agregarButton.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        agregarButton.setForeground(new java.awt.Color(255, 255, 255));
        agregarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logos/AgregarPro.PNG"))); // NOI18N
        agregarButton.setText("AGREGAR");
        agregarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarButtonActionPerformed(evt);
            }
        });

        eliminarButton.setBackground(new java.awt.Color(72, 36, 0));
        eliminarButton.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        eliminarButton.setForeground(new java.awt.Color(255, 255, 255));
        eliminarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logos/EliminarPro.PNG"))); // NOI18N
        eliminarButton.setText("ELIMINAR");
        eliminarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarButtonActionPerformed(evt);
            }
        });

        modificarButton.setBackground(new java.awt.Color(72, 36, 0));
        modificarButton.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        modificarButton.setForeground(new java.awt.Color(255, 255, 255));
        modificarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logos/CambiarPro.PNG"))); // NOI18N
        modificarButton.setText("MODIFICAR");
        modificarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarButtonActionPerformed(evt);
            }
        });

        buscarButton.setBackground(new java.awt.Color(72, 36, 0));
        buscarButton.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        buscarButton.setForeground(new java.awt.Color(255, 255, 255));
        buscarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logos/BuscarPro.PNG"))); // NOI18N
        buscarButton.setText("BUSCAR");
        buscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButtonActionPerformed(evt);
            }
        });

        regresarButton.setBackground(new java.awt.Color(72, 36, 0));
        regresarButton.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        regresarButton.setForeground(new java.awt.Color(255, 255, 255));
        regresarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logos/regresar.png"))); // NOI18N
        regresarButton.setText("Regresar");
        regresarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Georgia", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gestiones");

        jLabel3.setFont(new java.awt.Font("Georgia", 2, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre:");

        jLabel5.setFont(new java.awt.Font("Georgia", 2, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Precio: $");

        jLabel6.setFont(new java.awt.Font("Georgia", 2, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cadicudad:");

        jLabel7.setFont(new java.awt.Font("Georgia", 2, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Stock:");

        jLabel8.setFont(new java.awt.Font("Georgia", 2, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Categoria:");

        nom.setBackground(new java.awt.Color(97, 57, 17));
        nom.setFont(new java.awt.Font("Georgia", 2, 12)); // NOI18N
        nom.setForeground(new java.awt.Color(255, 255, 255));
     

        price.setBackground(new java.awt.Color(97, 57, 17));
        price.setFont(new java.awt.Font("Georgia", 2, 12)); // NOI18N
        price.setForeground(new java.awt.Color(255, 255, 255));
       

        cad.setBackground(new java.awt.Color(97, 57, 17));
        cad.setFont(new java.awt.Font("Georgia", 2, 12)); // NOI18N
        cad.setForeground(new java.awt.Color(255, 255, 255));
        cad.setText("dd/MM/yyyy");
            

        cant.setBackground(new java.awt.Color(97, 57, 17));
        cant.setFont(new java.awt.Font("Georgia", 2, 12)); // NOI18N
        cant.setForeground(new java.awt.Color(255, 255, 255));
           

        cat.setBackground(new java.awt.Color(97, 57, 17));
        cat.setFont(new java.awt.Font("Georgia", 2, 12)); // NOI18N
        cat.setForeground(new java.awt.Color(255, 255, 255));
        cat.setModel(new javax.swing.DefaultComboBoxModel<>(new Categoria[] { 
                null, 
                Categoria.HOGAR, 
                Categoria.ASEO, 
                Categoria.ROPA, 
                Categoria.COMESTIBLES 
            }));
        cat.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
       

        jLabel9.setFont(new java.awt.Font("Georgia", 2, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Codigo:");

        txtCod.setBackground(new java.awt.Color(97, 57, 17));
        txtCod.setFont(new java.awt.Font("Georgia", 2, 12)); // NOI18N
        txtCod.setForeground(new java.awt.Color(255, 255, 255));
        txtCod.setText("(solo para busquedad)");
     

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(modificarButton)
                            .addComponent(buscarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eliminarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(agregarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cant))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cad))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(price))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nom))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(regresarButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCod, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)))
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(agregarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(eliminarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(modificarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buscarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(regresarButton)
                .addGap(18, 18, 18))
        );

        jLabel2.setFont(new java.awt.Font("Georgia", 2, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PRODUCTOS");

        jTable1.setBackground(new java.awt.Color(72, 36, 0));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Codigo", "Precio", "Caducidad", "Stock", "Categoria"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(115, 73, 32));
        jTable1.setSelectionBackground(new java.awt.Color(174, 133, 92));
        jTable1.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(135, 135, 135))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modificarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarButtonActionPerformed
       String codigoBB = txtCod.getText();
        
        String nombreProd = nom.getText();
       double precioProd = Double.parseDouble(price.getText());
       DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
       LocalDate fechaProd = LocalDate.parse(cad.getText());
       int StockProd = Integer.parseInt(cant.getText());
       Categoria categoriaProd = (Categoria) cat.getSelectedItem();
       
       control.modificarProducto(codigoBB, new Productos(nombreProd, precioProd, fechaProd,categoriaProd, StockProd));
       cargarTabla();
       limpiarCampos();
    }//GEN-LAST:event_modificarButtonActionPerformed

    private void regresarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarButtonActionPerformed
        this.dispose();
        vp.setVisible(true);
    }//GEN-LAST:event_regresarButtonActionPerformed

    private void agregarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarButtonActionPerformed
       String nombreProd = nom.getText();
       double precioProd = Double.parseDouble(price.getText());
       DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
       LocalDate fechaProd = LocalDate.parse(cad.getText(),formatter );
       int StockProd = Integer.parseInt(cant.getText());
       Categoria categoriaProd = (Categoria) cat.getSelectedItem();
       
       control.agregarProducto(new Productos(nombreProd, precioProd, fechaProd,categoriaProd, StockProd));
       cargarTabla();
       limpiarCampos();
    }//GEN-LAST:event_agregarButtonActionPerformed
    private void eliminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarButtonActionPerformed
         String codigoBB = txtCod.getText();
         control.eliminarProducto(codigoBB);
         
         cargarTabla();
         limpiarCampos();
    }//GEN-LAST:event_eliminarButtonActionPerformed

    private void buscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButtonActionPerformed
        String codProd = txtCod.getText();
        Productos busqueda = control.buscarProducto(codProd);
        if (busqueda != null){
            nom.setText(busqueda.getNombre());
           price.setText(String.valueOf(busqueda.getPrecio()));
           cad.setText(String.valueOf(busqueda.getCaducidad()));
           cant.setText(String.valueOf(busqueda.getStock()));
           cat.setSelectedItem(busqueda.getCategoria());
           
           try {
                    throw new NotificarExito(exito);
                } catch (NotificarExito e) {
                    exito.setVisible(true);
                }
         }else{
             try {
            throw new CodigoNoEncontrado(noEncontrado);
        } catch (CodigoNoEncontrado e) {
        	noEncontrado.setVisible(true);
        }
            
        }
    }//GEN-LAST:event_buscarButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarButton;
    private javax.swing.JButton buscarButton;
    private javax.swing.JTextField cad;
    private javax.swing.JTextField cant;
    private javax.swing.JComboBox<Categoria> cat;
    private javax.swing.JButton eliminarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton modificarButton;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField price;
    private javax.swing.JButton regresarButton;
    private javax.swing.JTextField txtCod;
    // End of variables declaration//GEN-END:variables

    private void limpiarCampos (){
        nom.setText(" ");
        price.setText(" ");
        cad.setText("dd/MM/yyyy");
        cant.setText(" ");
        cat.setSelectedIndex(0);
        txtCod.setText("(solo para busquedad)");
    }

    
    private void cargarTabla() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // Limpia la tabla
        
        ArrayList<Productos> listaProductos = control.mostrarProductos();
        for (Productos producto : listaProductos) {
            Object[] row = {
                producto.getNombre(),
                producto.getCodigo(),
                producto.getPrecio(),
                producto.getCaducidad(),
                producto.getStock(),
                producto.getCategoria()
            };
            model.addRow(row);
        }
    }
    
public class FondoPanel extends JPanel {
       
         @Override
       public void paint (Graphics g){
           ImageIcon imagen = new ImageIcon(getClass().getClassLoader().getResource("logos/fondo.jpg"));
           g.drawImage(imagen.getImage(), 0, 0,getWidth() , getHeight(), this);
           super.paintComponents(g);
        } 
    }
}
