/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import controller.EmpleadoController;
import controller.ProductoController;
import controller.ProveedoresController;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import repository.*;
import service.*;
import vistas.*;

/**
 *
 * @author NICOL VALERIA
 */
public class VentanaPrincipal extends javax.swing.JFrame {
         EmpleadosVistas ventanaEmp;
         ProveedoresVistas ventanaProv;
         ProductosVistas ventanaProduc;
         GestionDeVentas ventanaVen;
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        
        FondoPanel fondo = new FondoPanel();
        this.setContentPane(fondo);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ge = new javax.swing.JButton();
        gpr = new javax.swing.JButton();
        gpd = new javax.swing.JButton();
        gv = new javax.swing.JButton();
        cerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Georgia", 2, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ventana Principal");

        jLabel2.setFont(new java.awt.Font("Georgia", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("¡Bienvenido!");

        jLabel3.setFont(new java.awt.Font("Georgia", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("¡Por favor elija una de las siguientes opciones!");

        ge.setBackground(new java.awt.Color(72, 36, 0));
        ge.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        ge.setForeground(new java.awt.Color(255, 255, 255));
        ge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logos/GE.png"))); // NOI18N
        ge.setText("Gestionar Empleado");
        ge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geActionPerformed(evt);
            }
        });

        gpr.setBackground(new java.awt.Color(72, 36, 0));
        gpr.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        gpr.setForeground(new java.awt.Color(255, 255, 255));
        gpr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logos/GPd.png"))); // NOI18N
        gpr.setText("Gestionar Proveedores");
        gpr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gprActionPerformed(evt);
            }
        });

        gpd.setBackground(new java.awt.Color(72, 36, 0));
        gpd.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        gpd.setForeground(new java.awt.Color(255, 255, 255));
        gpd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logos/GPd.png"))); // NOI18N
        gpd.setText("Gestionar Productos");
        gpd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gpdActionPerformed(evt);
            }
        });

        gv.setBackground(new java.awt.Color(72, 36, 0));
        gv.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        gv.setForeground(new java.awt.Color(255, 255, 255));
        gv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logos/GV.png"))); // NOI18N
        gv.setText("Gestionar Ventas");
        gv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gvActionPerformed(evt);
            }
        });

        cerrar.setBackground(new java.awt.Color(72, 36, 0));
        cerrar.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        cerrar.setForeground(new java.awt.Color(255, 255, 255));
        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logos/cancelar.png"))); // NOI18N
        cerrar.setText("Cerrar");
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(140, 140, 140))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(287, 287, 287))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(gpd)
                                    .addComponent(ge))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addComponent(gpr))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(71, 71, 71)
                                        .addComponent(gv)))))
                        .addGap(155, 155, 155))))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(cerrar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ge)
                    .addComponent(gpr))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gpd)
                    .addComponent(gv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(cerrar)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void geActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geActionPerformed
        this.ventanaEmp = new EmpleadosVistas(new EmpleadoService(new EmpleadoRepository()));
        this.ventanaEmp.setVisible(true);
    }//GEN-LAST:event_geActionPerformed

    private void gprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gprActionPerformed
        this.ventanaProv = new ProveedoresVistas(new ProveedoresService(new ProveedoresRepository()));
        this.ventanaProv.setVisible(true);
    }//GEN-LAST:event_gprActionPerformed

    private void gpdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gpdActionPerformed
       this.ventanaProduc = new ProductosVistas(new ProductoService(new ProductoRepository()));
        this.ventanaProduc.setVisible(true);
    }//GEN-LAST:event_gpdActionPerformed

    private void gvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gvActionPerformed
        this.ventanaVen = new GestionDeVentas(new VentaService(new VentaRepository()));
        this.ventanaVen.setVisible(true);
    }//GEN-LAST:event_gvActionPerformed

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_cerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cerrar;
    private javax.swing.JButton ge;
    private javax.swing.JButton gpd;
    private javax.swing.JButton gpr;
    private javax.swing.JButton gv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

public class FondoPanel extends JPanel {
       
         @Override
       public void paint (Graphics g){
           ImageIcon imagen = new ImageIcon(getClass().getClassLoader().getResource("logos/fondo.jpg"));
           g.drawImage(imagen.getImage(), 0, 0,getWidth() , getHeight(), this);
           super.paintComponents(g);
        } 
    }

}
